version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 9121:80
    environment:
      WORDPRESS_DB_HOST: localhost
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: n#H*gtQVYD0%
      WORDPRESS_DB_NAME: eventos
    volumes:
      - wordpress:/var/www/html
    depends_on: 
      - localhost

  localhost:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: eventos
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: n#H*gtQVYD0%
      
      
    volumes:
      - wp_db:/var/lib/mysql

volumes:
  wordpress:
  localhost:
