version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 9111:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: terminatortide
      WORDPRESS_DB_PASSWORD: n#H*gtQVYD0%
      WORDPRESS_DB_NAME: eventos
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: eventos
      MYSQL_USER: terminatortide
      MYSQL_PASSWORD: n#H*gtQVYD0%
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
