version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 9211:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 147852
      WORDPRESS_DB_NAME: eventos
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: eventos
      MYSQL_USER: admin
      MYSQL_PASSWORD: 147852
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
