version: '3.1'

services:

  production-nginx-container:
    container_name: 'production-nginx-container'
    image: nginx:latest
    ports:
      - "8701:80"
      - "443"
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./production-site:/usr/share/nginx/html
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/detin.saude.am.gov.br:8701/fullchain.pem:/etc/letsencrypt/live/detin.saude.am.gov.br:8701fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/detin.saude.am.gov.br:8701/privkey.pem:/etc/letsencrypt/live/detin.saude.am.gov.br:8701/privkey.pem
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
