version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 9121:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
    =
      WORDPRESS_DB_NAME: ev
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ev
      MYSQL_USER: root
      
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
